name: Docker Build & Push

on:
  push:
    branches:
      - main
      - qa
      - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DOCKER

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set image tag
        id: tag
        run: echo "IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: your-dockerhub-username/your-image-name:${{ env.IMAGE_TAG }}
          no-cache: true
          provenance: false

      - name: Done
        run: echo "✅ Deployed image for branch: ${{ env.IMAGE_TAG }}"
